
emailFolder: /Users/ghys/Documents/Mes Emails

accounts:

  -
    name: Les Roses
    group: true  # group by email
    recover: false # do not reload a delete email
    login: tartine300@lesroses-vacances.fr
    password: .............
    server: mail.gandi.net
    port: 993
    imapOutFolder:
      - Sent Messages
      - Éléments envoyés
    imapInFolder:
      - INBOX

  -
    name: Gcrespe
    group: true  # group by email
    recover: false # do not reload a delete email
    login: gcrespe@free.fr
    password: ......
    server: imap.free.fr
    port: 993
    imapOutFolder:
      - Sent
      - Sent Messages
    imapInFolder:
      - INBOX
      
  -
    name: Kiwi
    group: true  # group by email
    recover: false # do not reload a delete email
    login: kiwi@tartine.top
    password: .......
    server: mail.gandi.net
    port: 993
    imapOutFolder:
      - Sent
      - Éléments envoyés
    imapInFolder:
      - INBOX
      
      
